/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Telas;

import Model.Apartamento;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.dao.ApartamentoDAO;

/**
 *
 * @author Lucas
 */
public class TelaCadastroApartamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroApartamento
     */
    public TelaCadastroApartamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        txtEndereco8 = new javax.swing.JLabel();
        txtCondominio8 = new javax.swing.JLabel();
        txtRegiao8 = new javax.swing.JLabel();
        txtQuartos8 = new javax.swing.JLabel();
        txtVagas8 = new javax.swing.JLabel();
        txtPreco8 = new javax.swing.JLabel();
        txtAndares8 = new javax.swing.JLabel();
        txtAndar8 = new javax.swing.JLabel();
        txtM28 = new javax.swing.JLabel();
        txtBanheiros8 = new javax.swing.JLabel();
        txtIptu8 = new javax.swing.JLabel();
        txtSuites8 = new javax.swing.JLabel();
        txtElevador8 = new javax.swing.JLabel();
        txtMobilia8 = new javax.swing.JLabel();
        txtGaragem8 = new javax.swing.JLabel();
        txtVaranda8 = new javax.swing.JLabel();
        txtProprietario8 = new javax.swing.JLabel();
        jCheckBoxMobilia8 = new javax.swing.JCheckBox();
        jCheckBoxGaragem8 = new javax.swing.JCheckBox();
        jCheckBoxElevador8 = new javax.swing.JCheckBox();
        jtxtfEndereco8 = new javax.swing.JTextField();
        jtxtfRegiao8 = new javax.swing.JTextField();
        jftxtfBanheiros8 = new javax.swing.JFormattedTextField();
        jftxtfSuites8 = new javax.swing.JFormattedTextField();
        jftxtfVagas8 = new javax.swing.JFormattedTextField();
        jftxtfAndar8 = new javax.swing.JFormattedTextField();
        jtxtfCondominio8 = new javax.swing.JTextField();
        jftxtfQuartos8 = new javax.swing.JFormattedTextField();
        jftxtfM28 = new javax.swing.JFormattedTextField();
        jtxtIptu8 = new javax.swing.JTextField();
        jtxtPreco8 = new javax.swing.JTextField();
        jftxtfAndares8 = new javax.swing.JFormattedTextField();
        jtxtProprietario8 = new javax.swing.JTextField();
        jCheckBoxVaranda8 = new javax.swing.JCheckBox();
        jBtnCadastrar = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jbtnSalvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        txtEndereco8.setText("Endereco");

        txtCondominio8.setText("Condominio");

        txtRegiao8.setText("Regiao");

        txtQuartos8.setText("Quartos");

        txtVagas8.setText("Vagas");

        txtPreco8.setText("Preco");

        txtAndares8.setText("Andares");

        txtAndar8.setText("Andar");

        txtM28.setText("m2");

        txtBanheiros8.setText("Banheiros");

        txtIptu8.setText("IPTU");

        txtSuites8.setText("Suites");

        txtElevador8.setText("Elevador");

        txtMobilia8.setText("Mobilia");

        txtGaragem8.setText("Garagem");

        txtVaranda8.setText("Varanda");

        txtProprietario8.setText("Proprietario");

        jCheckBoxMobilia8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMobiliaActionPerformed(evt);
            }
        });

        jCheckBoxGaragem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGaragemActionPerformed(evt);
            }
        });

        jCheckBoxElevador8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxElevador8ActionPerformed(evt);
            }
        });

        jtxtfRegiao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfRegiao8ActionPerformed(evt);
            }
        });

        jftxtfBanheiros8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jftxtfBanheiros8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxtfBanheiros8ActionPerformed(evt);
            }
        });

        jftxtfSuites8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jftxtfSuites8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxtfSuitesActionPerformed(evt);
            }
        });

        jftxtfVagas8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jftxtfVagas8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxtfVagasActionPerformed(evt);
            }
        });

        jftxtfAndar8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jftxtfAndar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxtfAndar8ActionPerformed(evt);
            }
        });

        jtxtfCondominio8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfCondominioActionPerformed(evt);
            }
        });

        jftxtfQuartos8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jftxtfQuartos8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxtfQuartosActionPerformed(evt);
            }
        });

        jftxtfM28.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jftxtfM28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxtfM28ActionPerformed(evt);
            }
        });

        jtxtIptu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIptuActionPerformed(evt);
            }
        });

        jftxtfAndares8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jftxtfAndares8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxtfAndares8ActionPerformed(evt);
            }
        });

        jtxtProprietario8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtProprietarioActionPerformed(evt);
            }
        });

        jCheckBoxVaranda8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxVarandaActionPerformed(evt);
            }
        });

        jBtnCadastrar.setText("Cadastrar");
        jBtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadastrarActionPerformed(evt);
            }
        });

        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jbtnSalvar.setText("Salvar");
        jbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarActionPerformed(evt);
            }
        });

        jButton1.setText("Deletar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tabela");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Permanente");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jftxtfBanheiros8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEndereco8)
                                        .addComponent(jtxtfEndereco8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtfRegiao8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jftxtfSuites8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(txtCondominio8)
                                        .addGap(69, 69, 69)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(txtMobilia8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtGaragem8))
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jCheckBoxMobilia8)
                                                .addGap(55, 55, 55)
                                                .addComponent(jCheckBoxGaragem8)
                                                .addGap(0, 9, Short.MAX_VALUE))))
                                    .addComponent(jtxtfCondominio8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVaranda8)
                                        .addGap(18, 18, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBoxVaranda8)
                                        .addGap(28, 28, 28)))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jftxtfAndar8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jftxtfVagas8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jftxtfAndares8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(jCheckBoxElevador8)
                                                .addGap(50, 50, 50)
                                                .addComponent(jtxtProprietario8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jtxtPreco8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(238, 238, 238)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBtnCadastrar)
                                            .addComponent(jButton1)
                                            .addComponent(jButton3)))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(txtElevador8)
                                        .addGap(48, 48, 48)
                                        .addComponent(txtProprietario8)
                                        .addGap(65, 65, 65)
                                        .addComponent(txtPreco8)))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBtnExcluir)
                                    .addComponent(jbtnSalvar)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addGap(60, 60, 60))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtBanheiros8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtVagas8)
                                .addGap(292, 292, 292))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtRegiao8)
                                .addGap(465, 465, 465)
                                .addComponent(txtAndar8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtSuites8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAndares8)
                                .addGap(281, 281, 281)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQuartos8)
                            .addComponent(jtxtIptu8, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jftxtfM28)
                            .addComponent(txtM28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIptu8)
                            .addComponent(jftxtfQuartos8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jBtnAlterar)
                                .addGap(117, 117, 117))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(137, 137, 137))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(135, 135, 135))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndereco8)
                    .addComponent(txtCondominio8)
                    .addComponent(txtMobilia8)
                    .addComponent(txtGaragem8)
                    .addComponent(txtVaranda8)
                    .addComponent(txtElevador8)
                    .addComponent(txtProprietario8)
                    .addComponent(txtPreco8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtfEndereco8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtfCondominio8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBoxMobilia8)
                    .addComponent(jCheckBoxGaragem8)
                    .addComponent(jCheckBoxElevador8)
                    .addComponent(jCheckBoxVaranda8)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtProprietario8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtPreco8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQuartos8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRegiao8)
                        .addComponent(txtAndar8)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtfRegiao8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftxtfQuartos8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftxtfAndar8))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnSalvar)
                            .addComponent(jButton1))
                        .addGap(53, 53, 53)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtM28)
                    .addComponent(txtBanheiros8)
                    .addComponent(txtVagas8))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftxtfBanheiros8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxtfM28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxtfVagas8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIptu8)
                            .addComponent(txtSuites8)
                            .addComponent(txtAndares8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jftxtfSuites8)
                            .addComponent(jtxtIptu8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftxtfAndares8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(194, 194, 194))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnCadastrar)
                            .addComponent(jBtnExcluir))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Endereco", "Condominio", "Regiao", "Quartos", "Banheiros", "m2", "Suites", "IPTU", "Vagas", "Preco", "Andar", "Andares", "Mobilia", "Garagem", "Varanda", "Elevador", "Proprietario", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtProprietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtProprietarioActionPerformed

    private void jtxtIptuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIptuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIptuActionPerformed

    private void jftxtfQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxtfQuartosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxtfQuartosActionPerformed

    private void jtxtfCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfCondominioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfCondominioActionPerformed

    private void jftxtfVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxtfVagasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxtfVagasActionPerformed

    private void jftxtfSuitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxtfSuitesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxtfSuitesActionPerformed

    private void jCheckBoxVarandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxVarandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxVarandaActionPerformed

    private void jCheckBoxGaragemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGaragemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxGaragemActionPerformed

    private void jCheckBoxMobiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMobiliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMobiliaActionPerformed

    private void jCheckBoxElevador8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxElevador8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxElevador8ActionPerformed

    private void jftxtfBanheiros8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxtfBanheiros8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxtfBanheiros8ActionPerformed

    private void jtxtfRegiao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfRegiao8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfRegiao8ActionPerformed

    private void jftxtfM28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxtfM28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxtfM28ActionPerformed

    private void jftxtfAndar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxtfAndar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxtfAndar8ActionPerformed

    private void jftxtfAndares8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxtfAndares8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxtfAndares8ActionPerformed

    private void jBtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadastrarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtmApartamento = (DefaultTableModel) jTable1.getModel();
        Apartamento apartamento = new Apartamento();

        Float preco = Float.valueOf(jtxtPreco8.getText());
        Float iptu = Float.valueOf(jtxtIptu8.getText());
        Integer m2 = Integer.valueOf(jftxtfM28.getText());
        Integer quartos = Integer.valueOf(jftxtfQuartos8.getText());
        Integer banheiros = Integer.valueOf(jftxtfBanheiros8.getText());
        Integer suites = Integer.valueOf(jftxtfSuites8.getText());
        Integer andares = Integer.valueOf(jftxtfAndares8.getText());
        Integer vagas = Integer.valueOf(jftxtfVagas8.getText());
        Integer andar = Integer.valueOf(jftxtfAndar8.getText());

        apartamento.setPreco(preco);
        apartamento.setM2(m2);
        apartamento.setIptu(iptu);
        apartamento.setQuartos(quartos);
        apartamento.setBanheiros(banheiros);
        apartamento.setSuites(suites);
        apartamento.setAndares(andares);
        apartamento.setCondominio(jtxtfCondominio8.getText());
        apartamento.setRegiao(jtxtfRegiao8.getText());
        apartamento.setEndereço(jtxtfEndereco8.getText());
        apartamento.setVagas(vagas);
        apartamento.setPropietario(jtxtProprietario8.getText());
        apartamento.setAndar(andar);
        apartamento.setGaragem(jCheckBoxGaragem8.isSelected());
        apartamento.setMobilia(jCheckBoxMobilia8.isSelected());
        apartamento.setVaranda(jCheckBoxVaranda8.isSelected());
        apartamento.setElevador(jCheckBoxElevador8.isSelected());

        Object[] dados = {apartamento.getEndereço(), apartamento.getCondominio(), apartamento.getRegiao(), apartamento.getQuartos(), apartamento.getBanheiros(), apartamento.getM2(), apartamento.getSuites(), apartamento.getIptu(), apartamento.getVagas(), apartamento.getPreco(), apartamento.getAndar(), apartamento.getAndares(), apartamento.getMobilia(), apartamento.getGaragem(), apartamento.getVaranda(), apartamento.getElevador(), apartamento.getPropietario()};
        dtmApartamento.addRow(dados);
    }//GEN-LAST:event_jBtnCadastrarActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1) {
            jTable1.setValueAt(jtxtfEndereco8.getText(), jTable1.getSelectedRow(), 0);
            jTable1.setValueAt(jtxtfCondominio8.getText(), jTable1.getSelectedRow(), 1);
            jTable1.setValueAt(jtxtfRegiao8.getText(), jTable1.getSelectedRow(), 2);
            jTable1.setValueAt(jftxtfQuartos8.getText(), jTable1.getSelectedRow(), 3);
            jTable1.setValueAt(jftxtfBanheiros8.getText(), jTable1.getSelectedRow(), 4);
            jTable1.setValueAt(jftxtfM28.getText(), jTable1.getSelectedRow(), 5);
            jTable1.setValueAt(jftxtfSuites8.getText(), jTable1.getSelectedRow(), 6);
            jTable1.setValueAt(jtxtIptu8.getText(), jTable1.getSelectedRow(), 7);
            jTable1.setValueAt(jftxtfVagas8.getText(), jTable1.getSelectedRow(), 8);
            jTable1.setValueAt(jtxtPreco8.getText(), jTable1.getSelectedRow(), 9);
            jTable1.setValueAt(jftxtfAndar8.getText(), jTable1.getSelectedRow(), 10);
            jTable1.setValueAt(jftxtfAndares8.getText(), jTable1.getSelectedRow(), 11);
            jTable1.setValueAt(jCheckBoxMobilia8.isSelected(), jTable1.getSelectedRow(), 12);
            jTable1.setValueAt(jCheckBoxGaragem8.isSelected(), jTable1.getSelectedRow(), 13);
            jTable1.setValueAt(jCheckBoxVaranda8.isSelected(), jTable1.getSelectedRow(), 14);
            jTable1.setValueAt(jCheckBoxElevador8.isSelected(), jTable1.getSelectedRow(), 15);
            jTable1.setValueAt(jtxtProprietario8.getText(), jTable1.getSelectedRow(), 16);
        }

    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1) {
            DefaultTableModel dtmApartamento = (DefaultTableModel) jTable1.getModel();
            dtmApartamento.removeRow(jTable1.getSelectedRow());
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
        }

    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1) {
            jtxtfEndereco8.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            jtxtfCondominio8.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jtxtfRegiao8.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            jftxtfQuartos8.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
            jftxtfBanheiros8.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            jftxtfM28.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
            jftxtfSuites8.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            jtxtIptu8.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
            jftxtfVagas8.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
            jtxtPreco8.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
            jftxtfAndar8.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString());
            jftxtfAndares8.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 11).toString());
            jtxtProprietario8.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 16).toString());
            jCheckBoxMobilia8.setSelected((boolean) jTable1.getValueAt(jTable1.getSelectedRow(), 12));
            jCheckBoxGaragem8.setSelected((boolean) jTable1.getValueAt(jTable1.getSelectedRow(), 13));
            jCheckBoxVaranda8.setSelected((boolean) jTable1.getValueAt(jTable1.getSelectedRow(), 14));
            jCheckBoxElevador8.setSelected((boolean) jTable1.getValueAt(jTable1.getSelectedRow(), 15));
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarActionPerformed
        // TODO add your handling code here:
        Apartamento apartamento = new Apartamento();

        Float preco = Float.valueOf(jtxtPreco8.getText());
        Float iptu = Float.valueOf(jtxtIptu8.getText());
        Integer m2 = Integer.valueOf(jftxtfM28.getText());
        Integer quartos = Integer.valueOf(jftxtfQuartos8.getText());
        Integer banheiros = Integer.valueOf(jftxtfBanheiros8.getText());
        Integer suites = Integer.valueOf(jftxtfSuites8.getText());
        Integer andares = Integer.valueOf(jftxtfAndares8.getText());
        Integer vagas = Integer.valueOf(jftxtfVagas8.getText());
        Integer andar = Integer.valueOf(jftxtfAndar8.getText());

        apartamento.setPreco(preco);
        apartamento.setM2(m2);
        apartamento.setIptu(iptu);
        apartamento.setQuartos(quartos);
        apartamento.setBanheiros(banheiros);
        apartamento.setSuites(suites);
        apartamento.setAndares(andares);
        apartamento.setCondominio(jtxtfCondominio8.getText());
        apartamento.setRegiao(jtxtfRegiao8.getText());
        apartamento.setEndereço(jtxtfEndereco8.getText());
        apartamento.setVagas(vagas);
        apartamento.setPropietario(jtxtProprietario8.getText());
        apartamento.setAndar(andar);
        apartamento.setGaragem(jCheckBoxGaragem8.isSelected());
        apartamento.setMobilia(jCheckBoxMobilia8.isSelected());
        apartamento.setVaranda(jCheckBoxVaranda8.isSelected());
        apartamento.setElevador(jCheckBoxElevador8.isSelected());

        ApartamentoDAO cdao = new ApartamentoDAO();
        cdao.salvar(apartamento);
    }//GEN-LAST:event_jbtnSalvarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtmApt = (DefaultTableModel) jTable1.getModel();
        dtmApt.setRowCount(0);
        ApartamentoDAO cdao = new ApartamentoDAO();

        for (Apartamento c : cdao.buscar()) {

            Object[] dados = {c.getEndereço(), c.getCondominio(), c.getRegiao(), c.getQuartos(), c.getBanheiros(), c.getM2(), c.getSuites(),
                c.getIptu(), c.getVagas(), c.getPreco(), c.getAndar(), c.getAndares(), c.getMobilia(), c.getGaragem(),
                c.getVaranda(), c.getElevador(), c.getPropietario(),c.getId()};
            dtmApt.addRow(dados);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1) {
            Apartamento apartamento = new Apartamento();

            Float preco = Float.valueOf(jtxtPreco8.getText());
            Float iptu = Float.valueOf(jtxtIptu8.getText());
            Integer m2 = Integer.valueOf(jftxtfM28.getText());
            Integer quartos = Integer.valueOf(jftxtfQuartos8.getText());
            Integer banheiros = Integer.valueOf(jftxtfBanheiros8.getText());
            Integer suites = Integer.valueOf(jftxtfSuites8.getText());
            Integer andares = Integer.valueOf(jftxtfAndares8.getText());
            Integer vagas = Integer.valueOf(jftxtfVagas8.getText());
            Integer andar = Integer.valueOf(jftxtfAndar8.getText());

            apartamento.setPreco(preco);
            apartamento.setM2(m2);
            apartamento.setIptu(iptu);
            apartamento.setQuartos(quartos);
            apartamento.setBanheiros(banheiros);
            apartamento.setSuites(suites);
            apartamento.setAndares(andares);
            apartamento.setCondominio(jtxtfCondominio8.getText());
            apartamento.setRegiao(jtxtfRegiao8.getText());
            apartamento.setEndereço(jtxtfEndereco8.getText());
            apartamento.setVagas(vagas);
            apartamento.setPropietario(jtxtProprietario8.getText());
            apartamento.setAndar(andar);
            apartamento.setGaragem(jCheckBoxGaragem8.isSelected());
            apartamento.setMobilia(jCheckBoxMobilia8.isSelected());
            apartamento.setVaranda(jCheckBoxVaranda8.isSelected());
            apartamento.setElevador(jCheckBoxElevador8.isSelected());
            apartamento.setId((int)jTable1.getValueAt(jTable1.getSelectedRow(), 17));


            ApartamentoDAO cdao = new ApartamentoDAO();
            cdao.alterar(apartamento);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            if (jTable1.getSelectedRow() != -1) {
                Apartamento c = new Apartamento();
                c.setId((int)jTable1.getValueAt(jTable1.getSelectedRow(), 17));
                ApartamentoDAO cdao = new ApartamentoDAO();
                cdao.excluir(c);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCadastrar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBoxElevador8;
    private javax.swing.JCheckBox jCheckBoxGaragem8;
    private javax.swing.JCheckBox jCheckBoxMobilia8;
    private javax.swing.JCheckBox jCheckBoxVaranda8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JFormattedTextField jftxtfAndar8;
    private javax.swing.JFormattedTextField jftxtfAndares8;
    private javax.swing.JFormattedTextField jftxtfBanheiros8;
    private javax.swing.JFormattedTextField jftxtfM28;
    private javax.swing.JFormattedTextField jftxtfQuartos8;
    private javax.swing.JFormattedTextField jftxtfSuites8;
    private javax.swing.JFormattedTextField jftxtfVagas8;
    private javax.swing.JTextField jtxtIptu8;
    private javax.swing.JTextField jtxtPreco8;
    private javax.swing.JTextField jtxtProprietario8;
    private javax.swing.JTextField jtxtfCondominio8;
    private javax.swing.JTextField jtxtfEndereco8;
    private javax.swing.JTextField jtxtfRegiao8;
    private javax.swing.JLabel txtAndar8;
    private javax.swing.JLabel txtAndares8;
    private javax.swing.JLabel txtBanheiros8;
    private javax.swing.JLabel txtCondominio8;
    private javax.swing.JLabel txtElevador8;
    private javax.swing.JLabel txtEndereco8;
    private javax.swing.JLabel txtGaragem8;
    private javax.swing.JLabel txtIptu8;
    private javax.swing.JLabel txtM28;
    private javax.swing.JLabel txtMobilia8;
    private javax.swing.JLabel txtPreco8;
    private javax.swing.JLabel txtProprietario8;
    private javax.swing.JLabel txtQuartos8;
    private javax.swing.JLabel txtRegiao8;
    private javax.swing.JLabel txtSuites8;
    private javax.swing.JLabel txtVagas8;
    private javax.swing.JLabel txtVaranda8;
    // End of variables declaration//GEN-END:variables
}
